<?php

return [
    'af' => ['name' => 'Afrikaans', 'native' => 'Afrikaans', 'code' => 'af'],
    'sq' => ['name' => 'Albanian', 'native' => 'Shqip', 'code' => 'sq'],
    'am' => ['name' => 'Amharic', 'native' => 'አማርኛ', 'code' => 'am'],
    'ar' => ['name' => 'Arabic', 'native' => 'العربية', 'code' => 'ar', 'active' => true],
    'hy' => ['name' => 'Armenian', 'native' => 'Հայերեն', 'code' => 'hy'],
    'az' => ['name' => 'Azerbaijani', 'native' => 'Azərbaycan', 'code' => 'az'],
    'eu' => ['name' => 'Basque', 'native' => 'Euskara', 'code' => 'eu'],
    'be' => ['name' => 'Belarusian', 'native' => 'Беларуская', 'code' => 'be'],
    'bn' => ['name' => 'Bengali', 'native' => 'বাংলা', 'code' => 'bn'],
    'bs' => ['name' => 'Bosnian', 'native' => 'Bosanski', 'code' => 'bs'],
    'bg' => ['name' => 'Bulgarian', 'native' => 'Български', 'code' => 'bg'],
    'my' => ['name' => 'Burmese', 'native' => 'မြန်မာစာ', 'code' => 'my'],
    'ca' => ['name' => 'Catalan', 'native' => 'Català', 'code' => 'ca'],
    'zh' => ['name' => 'Chinese (Simplified)', 'native' => '简体中文', 'code' => 'zh', 'active' => true],
    'zh-TW' => ['name' => 'Chinese (Traditional)', 'native' => '繁體中文', 'code' => 'zh-TW'],
    'co' => ['name' => 'Corsican', 'native' => 'Corsu', 'code' => 'co'],
    'hr' => ['name' => 'Croatian', 'native' => 'Hrvatski', 'code' => 'hr'],
    'cs' => ['name' => 'Czech', 'native' => 'Čeština', 'code' => 'cs'],
    'da' => ['name' => 'Danish', 'native' => 'Dansk', 'code' => 'da'],
    'nl' => ['name' => 'Dutch', 'native' => 'Nederlands', 'code' => 'nl'],
    'en' => ['name' => 'English', 'native' => 'English', 'code' => 'en', 'active' => true],
    'eo' => ['name' => 'Esperanto', 'native' => 'Esperanto', 'code' => 'eo'],
    'et' => ['name' => 'Estonian', 'native' => 'Eesti', 'code' => 'et'],
    'tl' => ['name' => 'Filipino (Tagalog)', 'native' => 'Filipino', 'code' => 'tl'],
    'fi' => ['name' => 'Finnish', 'native' => 'Suomi', 'code' => 'fi'],
    'fr' => ['name' => 'French', 'native' => 'Français', 'code' => 'fr', 'active' => true],
    'fy' => ['name' => 'Frisian', 'native' => 'Frysk', 'code' => 'fy'],
    'gl' => ['name' => 'Galician', 'native' => 'Galego', 'code' => 'gl'],
    'ka' => ['name' => 'Georgian', 'native' => 'ქართული', 'code' => 'ka'],
    'de' => ['name' => 'German', 'native' => 'Deutsch', 'code' => 'de', 'active' => true],
    'el' => ['name' => 'Greek', 'native' => 'Ελληνικά', 'code' => 'el'],
    'gu' => ['name' => 'Gujarati', 'native' => 'ગુજરાતી', 'code' => 'gu'],
    'ht' => ['name' => 'Haitian Creole', 'native' => 'Kreyòl Ayisyen', 'code' => 'ht'],
    'ha' => ['name' => 'Hausa', 'native' => 'Hausa', 'code' => 'ha'],
    'he' => ['name' => 'Hebrew', 'native' => 'עברית', 'code' => 'he'],
    'hi' => ['name' => 'Hindi', 'native' => 'हिन्दी', 'code' => 'hi'],
    'hu' => ['name' => 'Hungarian', 'native' => 'Magyar', 'code' => 'hu'],
    'is' => ['name' => 'Icelandic', 'native' => 'Íslenska', 'code' => 'is'],
    'ig' => ['name' => 'Igbo', 'native' => 'Igbo', 'code' => 'ig'],
    'id' => ['name' => 'Indonesian', 'native' => 'Bahasa Indonesia', 'code' => 'id'],
    'ga' => ['name' => 'Irish', 'native' => 'Gaeilge', 'code' => 'ga'],
    'it' => ['name' => 'Italian', 'native' => 'Italiano', 'code' => 'it'],
    'ja' => ['name' => 'Japanese', 'native' => '日本語', 'code' => 'ja'],
    'jv' => ['name' => 'Javanese', 'native' => 'Basa Jawa', 'code' => 'jv'],
    'kn' => ['name' => 'Kannada', 'native' => 'ಕನ್ನಡ', 'code' => 'kn'],
    'kk' => ['name' => 'Kazakh', 'native' => 'Қазақ', 'code' => 'kk'],
    'km' => ['name' => 'Khmer', 'native' => 'ខ្មែរ', 'code' => 'km'],
    'ko' => ['name' => 'Korean', 'native' => '한국어', 'code' => 'ko'],
    'ku' => ['name' => 'Kurdish (Kurmanji)', 'native' => 'Kurdî', 'code' => 'ku'],
    'ky' => ['name' => 'Kyrgyz', 'native' => 'Кыргызча', 'code' => 'ky'],
    'lo' => ['name' => 'Lao', 'native' => 'ລາວ', 'code' => 'lo'],
    'la' => ['name' => 'Latin', 'native' => 'Latina', 'code' => 'la'],
    'lv' => ['name' => 'Latvian', 'native' => 'Latviešu', 'code' => 'lv'],
    'lt' => ['name' => 'Lithuanian', 'native' => 'Lietuvių', 'code' => 'lt'],
    'lb' => ['name' => 'Luxembourgish', 'native' => 'Lëtzebuergesch', 'code' => 'lb'],
    'mk' => ['name' => 'Macedonian', 'native' => 'Македонски', 'code' => 'mk'],
    'mg' => ['name' => 'Malagasy', 'native' => 'Malagasy', 'code' => 'mg'],
    'ms' => ['name' => 'Malay', 'native' => 'Bahasa Melayu', 'code' => 'ms'],
    'ml' => ['name' => 'Malayalam', 'native' => 'മലയാളം', 'code' => 'ml'],
    'mt' => ['name' => 'Maltese', 'native' => 'Malti', 'code' => 'mt'],
    'mi' => ['name' => 'Maori', 'native' => 'Māori', 'code' => 'mi'],
    'mr' => ['name' => 'Marathi', 'native' => 'मराठी', 'code' => 'mr'],
    'mn' => ['name' => 'Mongolian', 'native' => 'Монгол', 'code' => 'mn'],
    'ne' => ['name' => 'Nepali', 'native' => 'नेपाली', 'code' => 'ne'],
    'no' => ['name' => 'Norwegian', 'native' => 'Norsk', 'code' => 'no'],
    'or' => ['name' => 'Odia (Oriya)', 'native' => 'ଓଡ଼ିଆ', 'code' => 'or'],
    'ps' => ['name' => 'Pashto', 'native' => 'پښتو', 'code' => 'ps'],
    'fa' => ['name' => 'Persian (Farsi)', 'native' => 'فارسی', 'code' => 'fa'],
    'pl' => ['name' => 'Polish', 'native' => 'Polski', 'code' => 'pl'],
    'pt' => ['name' => 'Portuguese', 'native' => 'Português', 'code' => 'pt', 'active' => true],
    'pa' => ['name' => 'Punjabi', 'native' => 'ਪੰਜਾਬੀ', 'code' => 'pa'],
    'qu' => ['name' => 'Quechua', 'native' => 'Runa Simi', 'code' => 'qu'],
    'ro' => ['name' => 'Romanian', 'native' => 'Română', 'code' => 'ro'],
    'ru' => ['name' => 'Russian', 'native' => 'Русский', 'code' => 'ru'],
    'sm' => ['name' => 'Samoan', 'native' => 'Gagana Samoa', 'code' => 'sm'],
    'gd' => ['name' => 'Scots Gaelic', 'native' => 'Gàidhlig', 'code' => 'gd'],
    'sr' => ['name' => 'Serbian', 'native' => 'Српски', 'code' => 'sr'],
    'st' => ['name' => 'Sesotho', 'native' => 'Sesotho', 'code' => 'st'],
    'sn' => ['name' => 'Shona', 'native' => 'ChiShona', 'code' => 'sn'],
    'sd' => ['name' => 'Sindhi', 'native' => 'سنڌي', 'code' => 'sd'],
    'si' => ['name' => 'Sinhala', 'native' => 'සිංහල', 'code' => 'si'],
    'sk' => ['name' => 'Slovak', 'native' => 'Slovenčina', 'code' => 'sk'],
    'sl' => ['name' => 'Slovenian', 'native' => 'Slovenščina', 'code' => 'sl'],
    'so' => ['name' => 'Somali', 'native' => 'Soomaali', 'code' => 'so'],
    'es' => ['name' => 'Spanish', 'native' => 'Español', 'code' => 'es', 'active' => true],
    'su' => ['name' => 'Sundanese', 'native' => 'Basa Sunda', 'code' => 'su'],
    'sw' => ['name' => 'Swahili', 'native' => 'Kiswahili', 'code' => 'sw', 'active' => true],
    'sv' => ['name' => 'Swedish', 'native' => 'Svenska', 'code' => 'sv'],
    'tg' => ['name' => 'Tajik', 'native' => 'Тоҷикӣ', 'code' => 'tg'],
    'ta' => ['name' => 'Tamil', 'native' => 'தமிழ்', 'code' => 'ta'],
    'tt' => ['name' => 'Tatar', 'native' => 'Татарча', 'code' => 'tt'],
    'te' => ['name' => 'Telugu', 'native' => 'తెలుగు', 'code' => 'te'],
    'th' => ['name' => 'Thai', 'native' => 'ไทย', 'code' => 'th'],
    'tr' => ['name' => 'Turkish', 'native' => 'Türkçe', 'code' => 'tr'],
    'tk' => ['name' => 'Turkmen', 'native' => 'Türkmen', 'code' => 'tk'],
    'uk' => ['name' => 'Ukrainian', 'native' => 'Українська', 'code' => 'uk'],
    'ur' => ['name' => 'Urdu', 'native' => 'اردو', 'code' => 'ur'],
    'ug' => ['name' => 'Uyghur', 'native' => 'ئۇيغۇرچە', 'code' => 'ug'],
    'uz' => ['name' => 'Uzbek', 'native' => 'Oʻzbek', 'code' => 'uz'],
    'vi' => ['name' => 'Vietnamese', 'native' => 'Tiếng Việt', 'code' => 'vi'],
    'cy' => ['name' => 'Welsh', 'native' => 'Cymraeg', 'code' => 'cy'],
    'xh' => ['name' => 'Xhosa', 'native' => 'isiXhosa', 'code' => 'xh'],
    'yi' => ['name' => 'Yiddish', 'native' => 'ייִדיש', 'code' => 'yi'],
    'yo' => ['name' => 'Yoruba', 'native' => 'Yorùbá', 'code' => 'yo'],
    'zu' => ['name' => 'Zulu', 'native' => 'isiZulu', 'code' => 'zu'],
];
